name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        run: npm install

      - name: Sync Capacitor
        run: npx cap sync ios

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios/App
          pod init
          pod install

      - name: Build iOS
        run: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO